# Generated by Django 4.2.22 on 2025-11-16
import uuid
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0107_migrate_filters_to_rich_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Time spent in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "logged_date",
                    models.DateField(help_text="Date when the work was performed"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        help_text="Optional notes about the work done",
                    ),
                ),
                (
                    "billable",
                    models.BooleanField(
                        default=False, help_text="Whether this time is billable"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="db.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "db_table": "time_logs",
                "ordering": ("-logged_date", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["issue", "logged_date"], name="time_logs_issue_i_6a7b3e_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["user", "logged_date"], name="time_logs_user_id_44e7c8_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["workspace", "logged_date"], name="time_logs_workspa_8f2d9a_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["project", "logged_date"], name="time_logs_project_3c1e5f_idx"),
        ),
    ]
