# Generated by Django 4.2.21 on 2025-11-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0107_migrate_filters_to_rich_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("workspace", "Workspace"), ("project", "Project")],
                        default="workspace",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(blank=True, default=dict)),
                ("content_binary", models.BinaryField(null=True)),
                ("content_html", models.TextField(blank=True, default="<p></p>")),
                ("logo_props", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_page_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_templates",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_page_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_templates",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Template",
                "verbose_name_plural": "Page Templates",
                "db_table": "page_templates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="pagetemplate",
            index=models.Index(
                fields=["workspace", "scope"], name="page_template_ws_scope_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagetemplate",
            index=models.Index(fields=["project"], name="page_template_project_idx"),
        ),
    ]
