# Generated by Django 4.2.21 on 2025-11-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_default_project_states(apps, schema_editor):
    """Create default project states for all existing workspaces"""
    ProjectState = apps.get_model("db", "ProjectState")
    Workspace = apps.get_model("db", "Workspace")

    default_states = [
        {"name": "Draft", "group": "draft", "color": "#6b7280", "sequence": 15000},
        {"name": "Planning", "group": "planning", "color": "#3b82f6", "sequence": 30000},
        {"name": "Execution", "group": "execution", "color": "#f59e0b", "sequence": 45000},
        {"name": "Monitoring", "group": "monitoring", "color": "#8b5cf6", "sequence": 60000},
        {"name": "Completed", "group": "completed", "color": "#22c55e", "sequence": 75000},
        {"name": "Cancelled", "group": "cancelled", "color": "#ef4444", "sequence": 90000},
    ]

    for workspace in Workspace.objects.all():
        for state_data in default_states:
            ProjectState.objects.create(
                workspace=workspace,
                name=state_data["name"],
                group=state_data["group"],
                color=state_data["color"],
                sequence=state_data["sequence"],
                description=f"{state_data['name']} state for projects",
                slug=state_data["name"].lower(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0107_migrate_filters_to_rich_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectState",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Project State Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Project State Description"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3f76ff",
                        max_length=255,
                        verbose_name="Project State Color",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("sequence", models.FloatField(default=65535)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planning", "Planning"),
                            ("execution", "Execution"),
                            ("monitoring", "Monitoring"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project State",
                "verbose_name_plural": "Project States",
                "db_table": "project_states",
                "ordering": ("sequence",),
            },
        ),
        migrations.AddConstraint(
            model_name="projectstate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "workspace"),
                name="project_state_unique_name_workspace_when_deleted_at_null",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="db.projectstate",
            ),
        ),
        migrations.RunPython(create_default_project_states, migrations.RunPython.noop),
    ]
