# Generated by Django 4.2.22 on 2025-11-16 13:00
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0107_migrate_filters_to_rich_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItemTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Template Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Template Description"
                    ),
                ),
                (
                    "properties",
                    models.JSONField(default=dict, verbose_name="Template Properties"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Usage Count"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "sort_order",
                    models.FloatField(default=65535, verbose_name="Sort Order"),
                ),
                (
                    "external_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_work_item_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_item_templates",
                        to="db.issuetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Template",
                "verbose_name_plural": "Work Item Templates",
                "db_table": "work_item_templates",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="workitemtemplate",
            index=models.Index(
                fields=["project", "deleted_at"], name="work_item_t_project_c8e4cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitemtemplate",
            index=models.Index(
                fields=["workspace", "deleted_at"], name="work_item_t_workspa_e7f9a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitemtemplate",
            index=models.Index(
                fields=["type", "deleted_at"], name="work_item_t_type_id_4a2b5c_idx"
            ),
        ),
    ]
